GET http://localhost:3000/objects

###

GET http://localhost:3000/objects/byid/2345678

###

POST http://localhost:3000/objects
Content-Type: application/json

{
        "type": "villa",
        "location": "Long beach",
        "bedrooms": 1,
        "price": 2200000,
        "id": "5678901"
    }

###

PUT http://localhost:3000/objects/1234567
Content-Type: application/json

{
    "type": "villa",
    "location": "Klong Dao",
    "bedrooms": 2,
    "price": 3000000,
    "id": "1234567"
}

###

DELETE http://localhost:3000/objects/1234567


###

